import type { Lang } from '../lib/lang'

/**
 * Image registry. Every image is referenced by key.
 * Files live in /public/media as `<file>-<width>.webp` and are generated by
 * `npm run assets` (tools/import_images.py). `focus` = default object-position.
 */

export interface Media {
  file: string
  widths: number[]
  width: number
  height: number
  alt: Record<Lang, string>
  focus?: string
}

const shot = (file: string, width: number, height: number, en: string, ar: string, focus?: string, widths?: number[]): Media => ({
  file,
  width,
  height,
  widths: widths ?? [900, width],
  alt: { en, ar },
  focus,
})

const defs = {
  // ── art plates ─────────────────────────────────────────
  heroAurora: {
    file: 'hero-aurora',
    widths: [1280, 1672, 2400],
    width: 1672,
    height: 941,
    alt: {
      en: 'A lone figure on a mirror-still frozen lake beneath a vast aurora.',
      ar: 'شخص وحيد يقف على بحيرة متجمّدة صافية كالمرآة، تحت شفقٍ قطبيّ واسع.',
    },
    focus: '30% 50%',
  },
  aboutPortrait: {
    file: 'about-portrait',
    widths: [720, 1122],
    width: 1122,
    height: 1402,
    alt: { en: 'A silhouetted profile wrapped in ribbons of blue and green light.', ar: 'ظلّ وجهٍ جانبيّ تلتفّ حوله أشرطة من الضوء الأزرق والأخضر.' },
    focus: '50% 30%',
  },
  contactPlanet: {
    file: 'contact-planet',
    widths: [760, 1122],
    width: 1122,
    height: 1402,
    alt: { en: 'The luminous edge of a planet, a small figure drifting beside it.', ar: 'حافة كوكبٍ مضيئة، وإلى جانبها شخص صغير يسبح في الفضاء.' },
    focus: '55% 34%',
  },
  lightRibbons: {
    file: 'light-ribbons',
    widths: [720, 1122],
    width: 1122,
    height: 1402,
    alt: { en: 'Ribbons of green, cyan and violet light.', ar: 'أشرطة من الضوء الأخضر والفيروزي والبنفسجي.' },
  },

  // ── selected work ──────────────────────────────────────
  eloriaHome: shot('eloria-home', 1440, 900, 'Eloria — the home page of the novel library.', 'إيلوريا — الصفحة الرئيسية لمكتبة الروايات.', '50% 26%'),
  eloriaLibrary: shot('eloria-library', 1440, 900, 'Eloria — the library of novels with tags.', 'إيلوريا — مكتبة الروايات مع التصنيفات.'),
  eloriaSubscribe: shot('eloria-subscribe', 1440, 900, 'Eloria — readers subscribing to new chapters.', 'إيلوريا — اشتراك القرّاء في الفصول الجديدة.'),
  chessDesktop: shot('chess-desktop', 1280, 900, 'Pairing Board — search results shown as table-tent cards.', 'لوحة المواجهات — نتائج البحث على شكل بطاقات طاولة.', '50% 0%'),
  chessLive: shot('chess-live', 1440, 900, 'Pairing Board — a live round with every board.', 'لوحة المواجهات — جولة مباشرة بكل الطاولات.', '50% 30%'),
  chessMobile: shot('chess-mobile', 780, 1688, 'Pairing Board on a phone.', 'لوحة المواجهات على الجوال.', '50% 12%', [520, 780]),
  leapPhone: shot('leap-phone', 780, 1688, 'LEAP ONE — the dot-matrix face on a phone.', 'LEAP ONE — الوجه النقطي على الجوال.', '50% 0%', [520, 780]),
  leapDesktop: shot('leap-desktop', 660, 900, 'LEAP ONE — idle, ready for a question.', 'LEAP ONE — في وضع الانتظار، جاهز للسؤال.', '50% 0%', [660]),

  // ── the Computerjy Maher series ────────────────────────
  maherV1: shot('maher-v1', 1440, 900, 'Computerjy Maher v1 — the retro-terminal store in English.', 'كمبيوترجي ماهر ١ — المتجر بطابع الطرفية، بالإنجليزية.'),
  maherV1Ar: shot('maher-v1-ar', 1440, 900, 'Computerjy Maher v1 — the Arabic hero.', 'كمبيوترجي ماهر ١ — الواجهة العربية.'),
  maherV2: shot('maher-v2', 1440, 900, 'Computerjy Maher v2 — a first-person 3D gaming room.', 'كمبيوترجي ماهر ٢ — غرفة ألعاب ثلاثية الأبعاد من منظور الشخص الأول.'),
  maherV3: shot('maher-v3', 1440, 900, 'Computerjy Maher v3 — Night City, with the particle globe.', 'كمبيوترجي ماهر ٣ — مدينة الليل مع كرة الجسيمات.'),
  maherV3Products: shot('maher-v3-products', 1440, 900, 'Computerjy Maher v3 — products over the particle field.', 'كمبيوترجي ماهر ٣ — المنتجات فوق حقل الجسيمات.'),
  maherV4: shot('maher-v4', 1440, 900, 'Computerjy Maher OS — the desktop with a terminal open.', 'كمبيوترجي ماهر OS — سطح المكتب وفيه الطرفية مفتوحة.'),
  maherV4Door: shot('maher-v4-door', 1440, 900, 'Computerjy Maher OS — choosing a device at the door.', 'كمبيوترجي ماهر OS — اختيار الجهاز عند المدخل.'),
  maherV4Phone: shot('maher-v4-phone', 1440, 900, 'Computerjy Maher OS — the phone shell.', 'كمبيوترجي ماهر OS — واجهة الجوال.'),

  // ── certificates ───────────────────────────────────────
  certIbm: shot('cert-ibm', 1179, 902, 'IBM Full Stack Software Developer certificate.', 'شهادة IBM لمطوّر البرمجيات الشامل.', '50% 0%', [800, 1179]),
  certEcppt: shot('cert-ecppt', 1074, 800, 'eCPPT certificate from INE Security.', 'شهادة eCPPT من INE Security.', '50% 0%', [800, 1074]),
} satisfies Record<string, Media>

export type MediaKey = keyof typeof defs
export const media: Record<MediaKey, Media> = defs

export function srcSet(m: Media) {
  return m.widths.map((w) => `/media/${m.file}-${w}.webp ${w}w`).join(', ')
}

export function src(m: Media, w?: number) {
  const width = w ?? m.widths[m.widths.length - 1]
  return `/media/${m.file}-${width}.webp`
}
